--
-- CREATE TABLE "GROUPS"
--
CREATE TABLE GLDEV.GL_CORE_GROUPS
(
ID        			INTEGER NOT NULL ,
NAME	 			VARCHAR2 (250) ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_GROUPS ADD CONSTRAINT GL_CORE_GROUPS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "USERS"
--
CREATE TABLE GLDEV.GL_CORE_USERS
(
ID        			INTEGER NOT NULL ,
NAME	 			VARCHAR2 (250) ,
AVATAR	 			VARCHAR2 (250) ,
MAIL	 			VARCHAR2 (250) ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_USERS ADD CONSTRAINT GL_CORE_USERS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "GROUPS_USERS_MAP"
--
CREATE TABLE GLDEV.GL_CORE_GROUPS_USERS_MAP
(
ID        			INTEGER NOT NULL ,
GROUP_ID   			INTEGER NOT NULL ,
USER_ID   			INTEGER NOT NULL ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_GROUPS_USERS_MAP ADD CONSTRAINT GL_CORE_GROUPS_USERS_MAP_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "USER_AUTH_METHODS"
--
CREATE TABLE GLDEV.GL_CORE_USER_AUTH_METHODS
(
ID        			INTEGER NOT NULL ,
NAME	 			VARCHAR2 (100) ,
ICON	 			VARCHAR2 (250) ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_USER_AUTH_METHODS ADD CONSTRAINT GL_CORE_USER_AUTH_METHODS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "USER_AUTHS"
--
CREATE TABLE GLDEV.GL_CORE_USER_AUTHS
(
ID        			INTEGER NOT NULL ,
AUTH_ID        		INTEGER NOT NULL ,
USER_ID        		INTEGER NOT NULL ,
PASSWORD 			VARCHAR2 (250) ,
AVATAR	 			VARCHAR2 (250) ,
LASTNAME 			VARCHAR2 (250) ,
FIRSTNAME 			VARCHAR2 (250) ,
MAIL	 			VARCHAR2 (250) ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_USER_AUTHS ADD CONSTRAINT GL_CORE_USER_AUTHS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "PLUGINS"
--
CREATE TABLE GLDEV.GL_CORE_PLUGINS
(
ID        			INTEGER NOT NULL ,
NAME        		VARCHAR2 (250) ,
ACTIVATED        		INTEGER NOT NULL ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_PLUGINS ADD CONSTRAINT GL_CORE_PLUGINS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "PAGES"
--
CREATE TABLE GLDEV.GL_CORE_PAGES
(
ID        			INTEGER NOT NULL ,
PLUGIN_ID 			INTEGER NOT NULL ,
NAME        		VARCHAR2 (250) ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_PAGES ADD CONSTRAINT GL_CORE_PAGES_PK PRIMARY KEY
(
ID
);


--
-- CREATE TABLE "TABLES"
--
CREATE TABLE GLDEV.GL_CORE_TABLES
(
ID        			INTEGER NOT NULL ,
NAME        		VARCHAR2 (250) ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_TABLES ADD CONSTRAINT GL_CORE_TABLES_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "OBJECTS"
--
CREATE TABLE GLDEV.GL_CORE_OBJECTS
(
ID        			INTEGER NOT NULL ,
ID_TABLE   			INTEGER NOT NULL ,
ID_EXT     			INTEGER NOT NULL ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_OBJECTS ADD CONSTRAINT GL_CORE_OBJECTS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "ACCESS"
--
CREATE TABLE GLDEV.GL_CORE_ACCESS
(
ID        			INTEGER NOT NULL ,
ID_SOURCE  			INTEGER NOT NULL ,
ID_TARGET  			INTEGER NOT NULL ,
SECURE_LEVEL 		INTEGER NOT NULL ,
CREATED_DATE  		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_ACCESS ADD CONSTRAINT GL_CORE_ACCESS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "PARAMETERS"
--
CREATE TABLE GLDEV.GL_CORE_PARAMETERS
(
ID        			INTEGER NOT NULL ,
ID_PLUGIN  			INTEGER NOT NULL ,
NAME  				VARCHAR2 (250) ,
PARAMETER_VALUE		VARCHAR2 (250) ,
DEFAULT_VALUE		VARCHAR2 (250) ,
CREATED_DATE  		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_PARAMETERS ADD CONSTRAINT GL_CORE_PARAMETERS_PK PRIMARY KEY
(
ID
);

--
-- Création de la table PROCESSUS
--
CREATE TABLE GLDEV.GL_CORE_PROCESSUS
(
ID        			INTEGER NOT NULL ,
ID_PARENT 			INTEGER ,
CMD					VARCHAR2 (250) ,
ARGS				VARCHAR2 (250) ,
STATUS	 			VARCHAR2 (12) ,
PERCENT 			INTEGER NOT NULL ,
COMMENTS			VARCHAR2 (250) ,
TIMEOUT 			INTEGER NOT NULL,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_PROCESSUS ADD CONSTRAINT GL_CORE_PROCESSUS_PK PRIMARY KEY
(
ID
);

--
-- Création de la table JOB
--
CREATE TABLE GLDEV.GL_CORE_JOB
(
ID        			INTEGER NOT NULL ,
ID_PLUGIN 			INTEGER NOT NULL ,
PAGE				VARCHAR2 (250) ,
LAST_RUN_PID		INTEGER NOT NULL ,
LAST_RUN 			INTEGER NOT NULL ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_JOB ADD CONSTRAINT GL_CORE_JOB_PK PRIMARY KEY
(
ID
);

--
-- Création de la table JOB_SCHEDULED
--
CREATE TABLE GLDEV.GL_CORE_JOB_SCHEDULED
(
ID        			INTEGER NOT NULL ,
ID_JOB	 			INTEGER NOT NULL ,
START_DAY 			INTEGER NOT NULL ,
START_TIME 			INTEGER NOT NULL ,
POLLING_TRIGGER 	CLOB ,
POLLING_TIME		INTEGER NOT NULL ,
PAGE				VARCHAR2 (250) ,
LAST_RUN_PID		INTEGER NOT NULL ,
LAST_RUN 			INTEGER NOT NULL ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_JOB_SCHEDULED ADD CONSTRAINT GL_CORE_JOB_SCHEDULED_PK PRIMARY KEY
(
ID
);

--
-- Création de la table EVENT_LOGS
--
CREATE TABLE GLDEV.GL_CORE_EVENT_LOGS
(
ID        			INTEGER NOT NULL ,
ID_PLUGIN 			INTEGER NOT NULL ,
LOG_STATEMENT		VARCHAR2 (250) ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_ID   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CORE_EVENT_LOGS ADD CONSTRAINT GL_CORE_EVENT_LOGS_PK PRIMARY KEY
(
ID
);
