--
-- Plug in CMDB
--

--
-- CREATE TABLE "CMDB_ENVIRONMENTS"
--
CREATE TABLE GLDEV.GL_CMDB_ENVIRONMENTS
(
ID        		INTEGER NOT NULL ,
ID_PARENT  		INTEGER ,
NAME			VARCHAR2 (250) ,
CREATED_DATE 	INTEGER NOT NULL ,
EDITED_DATE  	INTEGER NOT NULL ,
DELETED_DATE 	INTEGER NOT NULL ,
CREATED_id   	INTEGER NOT NULL ,
EDITED_ID    	INTEGER NOT NULL ,
DELETED_ID   	INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CMDB_ENVIRONMENTS ADD CONSTRAINT GL_CMDB_ENVIRONMENTS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_PROJECTS"
--
CREATE TABLE GLDEV.GL_CMDB_PROJECTS
(
ID        		INTEGER NOT NULL ,
ID_PARENT  		INTEGER ,
NAME			VARCHAR2 (250) ,
COMMENTS		CLOB ,
CREATED_DATE 	INTEGER NOT NULL ,
EDITED_DATE  	INTEGER NOT NULL ,
DELETED_DATE 	INTEGER NOT NULL ,
CREATED_id   	INTEGER NOT NULL ,
EDITED_ID    	INTEGER NOT NULL ,
DELETED_ID   	INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CMDB_PROJECTS ADD CONSTRAINT GL_CMDB_PROJECTS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DEVICES"
--
CREATE TABLE GLDEV.GL_CMDB_DEVICES
(
ID           	INTEGER NOT NULL ,
ID_PARENT  		INTEGER ,
NAME         	VARCHAR2 (150) ,
TYPENAME        VARCHAR2 (50) ,
COMMENTS		CLOB ,
SERIAL_NUMBER  	VARCHAR2 (75) ,
CREATED_DATE 	INTEGER NOT NULL ,
EDITED_DATE  	INTEGER NOT NULL ,
DELETED_DATE 	INTEGER NOT NULL ,
CREATED_id   	INTEGER NOT NULL ,
EDITED_ID    	INTEGER NOT NULL ,
DELETED_ID   	INTEGER NOT NULL
) ;
ALTER TABLE GLDEV.GL_CMDB_DEVICES ADD CONSTRAINT GL_CMDB_DEVICES_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DEV_PRO_ENV_MAP"
--
CREATE TABLE GLDEV.GL_CMDB_DEV_PRO_ENV_MAP
(
ID        		INTEGER NOT NULL ,
ID_DEVICE  		INTEGER NOT NULL ,
ID_PROJECT 		INTEGER NOT NULL ,
ID_ENVIRONMENT	INTEGER NOT NULL ,
CREATED_DATE 	INTEGER NOT NULL ,
EDITED_DATE  	INTEGER NOT NULL ,
DELETED_DATE 	INTEGER NOT NULL ,
CREATED_id   	INTEGER NOT NULL ,
EDITED_ID    	INTEGER NOT NULL ,
DELETED_ID   	INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CMDB_DEV_PRO_ENV_MAP ADD CONSTRAINT CMDB_DEV_PRO_ENV_MAP_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DEV_STATUS"
--
CREATE TABLE GLDEV.GL_CMDB_DEV_STATUS
(
ID        		INTEGER NOT NULL ,
ID_DEVICE 		INTEGER NOT NULL ,
STATUS     	 	VARCHAR2 (20) ,
CODE     	 	VARCHAR2 (250) ,
CREATED_DATE 	INTEGER NOT NULL ,
EDITED_DATE  	INTEGER NOT NULL ,
DELETED_DATE 	INTEGER NOT NULL ,
CREATED_id   	INTEGER NOT NULL ,
EDITED_ID    	INTEGER NOT NULL ,
DELETED_ID   	INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CMDB_DEV_STATUS ADD CONSTRAINT GL_CMDB_DEV_STATUS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DEV_OS_CPU"
--
CREATE TABLE GLDEV.GL_CMDB_DEV_OS_CPU
(
ID           	INTEGER NOT NULL ,
ID_OS			INTEGER ,
LOGICAL_ID		VARCHAR2 (20) ,
MAX_CLOCK_SPEED	INTEGER ,
NAME         	VARCHAR2 (150) ,
CREATED_DATE 	INTEGER NOT NULL ,
EDITED_DATE  	INTEGER NOT NULL ,
DELETED_DATE 	INTEGER NOT NULL ,
CREATED_id   	INTEGER NOT NULL ,
EDITED_ID    	INTEGER NOT NULL ,
DELETED_ID   	INTEGER NOT NULL
) ;
ALTER TABLE GLDEV.GL_CMDB_DEV_OS_CPU ADD CONSTRAINT GL_CMDB_DEV_OS_CPU_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DEV_OS"
--
CREATE TABLE GLDEV.GL_CMDB_DEV_OS
(
ID           		INTEGER NOT NULL ,
ID_DEVICE			INTEGER ,
OS_TYPE         	VARCHAR2 (20) ,
OS_PORT         	INTEGER ,
OS_NAME    			VARCHAR2 (150) ,
OS_VERSION      	VARCHAR2 (150) ,
OS_ARCHITECTURE  	VARCHAR2 (10) ,
OS_SERIAL_NUMBER  	VARCHAR2 (100) ,
OS_INSTALL_DATE  	INTEGER NOT NULL ,
OS_LAST_BOOT_TIME  	INTEGER NOT NULL ,
OS_MEMORY_SIZE		INTEGER NOT NULL ,
AUDITED    		    INTEGER ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
) ;
ALTER TABLE GLDEV.GL_CMDB_DEV_OS ADD CONSTRAINT GL_CMDB_DEV_OS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DEV_OS_DISKS"
--
CREATE TABLE GLDEV.GL_CMDB_DEV_OS_DISKS
(
ID           		INTEGER NOT NULL ,
ID_OS			INTEGER ,
NAME         		VARCHAR2 (150) ,
INTERFACETYPE    	VARCHAR2 (25) ,
DISK_SIZE      		INTEGER ,
CAPTION				VARCHAR2 (250) ,
FIRMWAREREVISION  	VARCHAR2 (50) ,
MANUFACTURER  		VARCHAR2 (50) ,
MODEL  				VARCHAR2 (150) ,
SERIALNUMBER		VARCHAR2 (150) ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID  		INTEGER NOT NULL
) ;
ALTER TABLE GLDEV.GL_CMDB_DEV_OS_DISKS ADD CONSTRAINT GL_CMDB_DEV_OS_DISKS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DEV_OS_FS"
--
CREATE TABLE GLDEV.GL_CMDB_DEV_OS_FS
(
ID           		INTEGER NOT NULL ,
ID_OS			INTEGER ,
NAME         		VARCHAR2 (150) ,
FILESYSTEM    		VARCHAR2 (25) ,
ALIAS				VARCHAR2 (250) ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
) ;
ALTER TABLE GLDEV.GL_CMDB_DEV_OS_FS ADD CONSTRAINT GL_CMDB_DEV_OS_FS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DEV_OS_FS_UP"
--
CREATE TABLE GLDEV.GL_CMDB_DEV_OS_FS_UP
(
ID           		INTEGER NOT NULL ,
ID_FS				INTEGER ,
PARTITION_SIZE		INTEGER ,
PARTITION_FREESPACE	INTEGER ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
) ;
ALTER TABLE GLDEV.GL_CMDB_DEV_OS_FS_UP ADD CONSTRAINT GL_CMDB_DEV_OS_FS_UP_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DEV_OS_SERVICES"
--
CREATE TABLE GLDEV.GL_CMDB_DEV_OS_SERVICES
(
ID           		INTEGER NOT NULL ,
ID_OS			INTEGER ,
NAME         		VARCHAR2 (150) ,
PATH_NAME    		VARCHAR2 (150) ,
START_MODE			VARCHAR2 (20) ,
SERVICE_STATE		VARCHAR2 (15) ,
OWNER  				VARCHAR2 (50) ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
) ;
ALTER TABLE GLDEV.GL_CMDB_DEV_OS_SERVICES ADD CONSTRAINT GL_CMDB_DEV_OS_SERVICES_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DEV_OS_CREDS"
--
CREATE TABLE GLDEV.GL_CMDB_DEV_OS_CREDS
(
ID        				INTEGER NOT NULL ,
ID_OS 				INTEGER NOT NULL ,
USER_NAME     	 		VARCHAR2 (250) ,
PASS_WORD     	 		VARCHAR2 (250) ,
SUBSTITUTE_USER_NAME	VARCHAR2 (250) ,
SUBSTITUTE_PASS_WORD   	VARCHAR2 (250) ,
CREATED_DATE 			INTEGER NOT NULL ,
EDITED_DATE  			INTEGER NOT NULL ,
DELETED_DATE 			INTEGER NOT NULL ,
CREATED_id   			INTEGER NOT NULL ,
EDITED_ID    			INTEGER NOT NULL ,
DELETED_ID   			INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CMDB_DEV_OS_CREDS ADD CONSTRAINT GL_CMDB_DEV_OS_CREDS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DB_INSTANCES"
--
CREATE TABLE GLDEV.GL_CMDB_DB_INSTANCES
(
ID        		INTEGER NOT NULL ,
ID_OS	 		INTEGER NOT NULL ,
NAME     	 	VARCHAR2 (250) ,
DB_TYPE     	VARCHAR2 (30) ,
DB_VERSION		VARCHAR2 (25) ,
DB_PORT		 	INTEGER ,
DB_BIN_PATH     VARCHAR2 (150) ,
AUDITED    		INTEGER ,
CREATED_DATE 	INTEGER NOT NULL ,
EDITED_DATE  	INTEGER NOT NULL ,
DELETED_DATE 	INTEGER NOT NULL ,
CREATED_id   	INTEGER NOT NULL ,
EDITED_ID    	INTEGER NOT NULL ,
DELETED_ID   	INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CMDB_DB_INSTANCES ADD CONSTRAINT GL_CMDB_DB_INSTANCES_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DB_INSTANCE_STATUS"
--
CREATE TABLE GLDEV.GL_CMDB_DB_INSTANCE_UP
(
ID        		INTEGER NOT NULL ,
ID_INSTANCE 	INTEGER NOT NULL ,
STATUS     	 	VARCHAR2 (20) ,
CODE     	 	VARCHAR2 (250) ,
CREATED_DATE 	INTEGER NOT NULL ,
EDITED_DATE  	INTEGER NOT NULL ,
DELETED_DATE 	INTEGER NOT NULL ,
CREATED_id   	INTEGER NOT NULL ,
EDITED_ID    	INTEGER NOT NULL ,
DELETED_ID   	INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CMDB_DB_INSTANCE_UP ADD CONSTRAINT GL_CMDB_DB_INSTANCE_UP_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DB_INSTANCE_CREDS"
--
CREATE TABLE GLDEV.GL_CMDB_DB_INSTANCE_CREDS
(
ID        				INTEGER NOT NULL ,
ID_INSTANCE 			INTEGER NOT NULL ,
USER_NAME     	 		VARCHAR2 (250) ,
PASS_WORD     	 		VARCHAR2 (250) ,
SUBSTITUTE_USER_NAME	VARCHAR2 (250) ,
SUBSTITUTE_PASS_WORD   	VARCHAR2 (250) ,
CREATED_DATE 			INTEGER NOT NULL ,
EDITED_DATE  			INTEGER NOT NULL ,
DELETED_DATE 			INTEGER NOT NULL ,
CREATED_id   			INTEGER NOT NULL ,
EDITED_ID    			INTEGER NOT NULL ,
DELETED_ID   			INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CMDB_DB_INSTANCE_CREDS ADD CONSTRAINT GL_CMDB_DB_INSTANCE_CREDS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DATABASES"
--
CREATE TABLE GLDEV.GL_CMDB_DATABASES
(
ID        		INTEGER NOT NULL ,
ID_INSTANCE 	INTEGER NOT NULL ,
NAME     	 	VARCHAR2 (150) ,
STARTUP_TIME	INTEGER ,
STATUS			VARCHAR2 (10) ,
ARCHIVER		VARCHAR2 (10) ,
HEALTH_CHECKED  INTEGER NOT NULL ,
SPACE_CHECKED   INTEGER NOT NULL ,
BACKUP_CHECKED  INTEGER NOT NULL ,
CREATED_DATE 	INTEGER NOT NULL ,
EDITED_DATE  	INTEGER NOT NULL ,
DELETED_DATE 	INTEGER NOT NULL ,
CREATED_id   	INTEGER NOT NULL ,
EDITED_ID    	INTEGER NOT NULL ,
DELETED_ID   	INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CMDB_DATABASES ADD CONSTRAINT GL_CMDB_DATABASES_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DB_BACKUPS"
--
CREATE TABLE GLDEV.GL_CMDB_DB_BACKUPS
(
ID        			INTEGER NOT NULL ,
ID_DATABASE	 		INTEGER NOT NULL ,
BACKUP_FORMAT		VARCHAR2 (20) ,
BACKUP_TYPE			VARCHAR2 (20) ,
BACKUP_COMPLETION 	INTEGER ,
BACKUP_STATUS		VARCHAR2 (50) ,
BACKUP_SIZE 		INTEGER ,
BACKUP_FILE_PATH	VARCHAR2 (250) ,
CREATED_DATE 		INTEGER NOT NULL ,
EDITED_DATE  		INTEGER NOT NULL ,
DELETED_DATE 		INTEGER NOT NULL ,
CREATED_id   		INTEGER NOT NULL ,
EDITED_ID    		INTEGER NOT NULL ,
DELETED_ID   		INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CMDB_DB_BACKUPS ADD CONSTRAINT GL_CMDB_DB_BACKUPS_PK PRIMARY KEY
(
ID
);


--
-- CREATE TABLE "CMDB_DB_FILEGROUPS"
--
CREATE TABLE GLDEV.GL_CMDB_DB_FILEGROUPS
(
ID        		INTEGER NOT NULL ,
ID_DATABASE 	INTEGER NOT NULL ,
NAME     	 	VARCHAR2 (150) ,
CREATED_DATE 	INTEGER NOT NULL ,
EDITED_DATE  	INTEGER NOT NULL ,
DELETED_DATE 	INTEGER NOT NULL ,
CREATED_id   	INTEGER NOT NULL ,
EDITED_ID    	INTEGER NOT NULL ,
DELETED_ID   	INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CMDB_DB_FILEGROUPS ADD CONSTRAINT GL_CMDB_DB_FILEGROUPS_PK PRIMARY KEY
(
ID
);

--
-- CREATE TABLE "CMDB_DB_FILEGROUP_STATUS"
--
CREATE TABLE GLDEV.GL_CMDB_DB_FILEGROUP_STATUS
(
ID        		INTEGER NOT NULL ,
ID_FILEGROUP 	INTEGER NOT NULL ,
SPACE_SIZE 		INTEGER NOT NULL ,
FREE_SPACE		INTEGER NOT NULL ,
CREATED_DATE 	INTEGER NOT NULL ,
EDITED_DATE  	INTEGER NOT NULL ,
DELETED_DATE 	INTEGER NOT NULL ,
CREATED_id   	INTEGER NOT NULL ,
EDITED_ID    	INTEGER NOT NULL ,
DELETED_ID   	INTEGER NOT NULL
);
ALTER TABLE GLDEV.GL_CMDB_DB_FILEGROUP_STATUS ADD CONSTRAINT GL_CMDB_DB_FILEGROUP_STATUS_PK PRIMARY KEY
(
ID
);
